# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c78f4745c8993ff694f63b63f1cde7f3178965398ef7610f965ccf3088d32d9a1da46b86bf0a7175812c0be966bf91d24aa9b2beef21320e485268952fac1b0

test:
  secret_key_base: d487d9ae800707f8c704e28e122f9a675f3767171f23a9b629ee2e4e8777f96e508831348988f91ff40a7602d64bf201586572f5beea5045c4a4d1b863a49572

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
